# Default path for local RPMs
#local_rpm_base: "/home/CHAI_Sk/rpm-stack/utilities_rpm"

# Default modulepath to export (can override in playbook)
#modulepath_dir: "/home/apps/modulefiles/"

# Lmod and dependencies
custom_rpms:
  - lmod-hpc-8.2.10-15.1.hpc.2.0.x86_64.rpm
  - libcerf-1.17-2.el8.x86_64.rpm
  - libcerf-devel-1.17-2.el8.x86_64.rpm

# Packages to install
required_packages:
  - gcc-gfortran
  - curl
  - screen
  - figlet
  - cmake
  - lua
  - lua-posix
  - lua-libs
  - lua-filesystem

# Old package to remove
#old_modules_package: "environment-modules-4.5.2-4.el8.x86_64"

# HISTTIMEFORMAT line
histtimeformat_line: 'export HISTTIMEFORMAT="%F %T "'


old_modules_package: environment-modules
