---
###############################################################################
# Master HPC Provisioning – Enterprise Orchestrator
###############################################################################

- name: Master HPC Provisioning Playbook
  hosts: hpc_master
  gather_facts: no
  ignore_unreachable: yes
  become: true

  vars_files:
    - ../../../automation/ansible/group_vars/all.yml

  tasks:
    - name: Display starting banner
      ansible.builtin.debug:
        msg: "Starting HPC provisioning on {{ inventory_hostname }}"
      tags: [always]

# =======================================================================================================
# ==================================  PHASE 2: NETWORK CONFIGURATION  ===================================
# =======================================================================================================
- import_playbook: ../../../automation/ansible/playbook_library/network/network_manager.yml
  vars:
    nm_service_state: started   # Options: started, stopped, restarted
    nm_service_enabled: true    # true or false
    nm_install_if_missing: true  # true or false
