"""
OpenCHAI GUI - Inventory Generator
Converts in-memory Node list + ClusterConfig into an Ansible INI inventory
and writes it to disk.
"""

from __future__ import annotations

import logging
import os
from typing import List

from models import ClusterConfig, Node, NodeRole

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Group → NodeRole mapping
# ---------------------------------------------------------------------------

ROLE_TO_GROUP: dict[NodeRole, str] = {
    NodeRole.headnode:    "headnodes",
    NodeRole.compute:     "compute_nodes",
    NodeRole.gpu:         "gpu_nodes",
    NodeRole.storage:     "storage_nodes",
    NodeRole.login:       "login_nodes",
    NodeRole.management:  "management_nodes",
    NodeRole.service:     "service_nodes",
}


def generate_inventory(
    nodes: List[Node],
    config: ClusterConfig,
    output_path: str,
) -> str:
    """
    Generate an Ansible INI inventory file from the provided node list and
    cluster configuration, write it to *output_path*, and return the
    rendered content.
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    # Bucket nodes by role
    groups: dict[str, List[Node]] = {g: [] for g in ROLE_TO_GROUP.values()}
    for node in nodes:
        group = ROLE_TO_GROUP.get(node.role, "compute_nodes")
        groups[group].append(node)

    lines: List[str] = []

    # -----------------------------------------------------------------------
    # Header
    # -----------------------------------------------------------------------
    lines += [
        f"# OpenCHAI Ansible Inventory",
        f"# Cluster: {config.cluster_name}",
        f"# Auto-generated by OpenCHAI GUI — do not edit by hand",
        "",
    ]

    # -----------------------------------------------------------------------
    # Per-group host entries
    # -----------------------------------------------------------------------
    for group_name, group_nodes in groups.items():
        if not group_nodes:
            continue
        lines.append(f"[{group_name}]")
        for node in group_nodes:
            host_line = (
                f"{node.hostname}"
                f" ansible_host={node.ip_address}"
                f" ansible_user={config.ansible_user}"
                f" ansible_ssh_private_key_file={config.ansible_ssh_key}"
            )
            if node.bmc_ip:
                host_line += f" bmc_ip={node.bmc_ip}"
            if node.gpu_count and node.gpu_count > 0:
                host_line += f" gpu_count={node.gpu_count}"
            if node.gpu_model:
                host_line += f" gpu_model={node.gpu_model}"
            lines.append(host_line)
        lines.append("")

    # -----------------------------------------------------------------------
    # [all:vars]
    # -----------------------------------------------------------------------
    lines += [
        "[all:vars]",
        f"cluster_name={config.cluster_name}",
        f"headnode_ip={config.headnode_ip}",
        f"management_network={config.network.management_network}",
        f"ansible_user={config.ansible_user}",
        f"scheduler={config.scheduler.value}",
        f"nfs_enabled={'true' if config.services.nfs_enabled else 'false'}",
        f"slurm_enabled={'true' if config.services.slurm_enabled else 'false'}",
        f"ldap_enabled={'true' if config.services.ldap_enabled else 'false'}",
        f"monitoring_enabled={'true' if config.services.monitoring_enabled else 'false'}",
        f"infiniband_enabled={'true' if config.services.infiniband_enabled else 'false'}",
    ]
    if config.network.dns_server:
        lines.append(f"dns_server={config.network.dns_server}")
    if config.network.ntp_server:
        lines.append(f"ntp_server={config.network.ntp_server}")
    if config.services.ldap_server:
        lines.append(f"ldap_server={config.services.ldap_server}")
    if config.services.ldap_base_dn:
        lines.append(f"ldap_base_dn={config.services.ldap_base_dn}")

    lines.append("")

    # -----------------------------------------------------------------------
    # Convenience super-groups
    # -----------------------------------------------------------------------
    lines += [
        "[all_compute:children]",
        "compute_nodes",
        "gpu_nodes",
        "",
        "[cluster:children]",
        "headnodes",
        "compute_nodes",
        "gpu_nodes",
        "storage_nodes",
        "login_nodes",
        "management_nodes",
        "service_nodes",
        "",
    ]

    content = "\n".join(lines)

    with open(output_path, "w") as fh:
        fh.write(content)

    logger.info("Inventory written to %s (%d nodes)", output_path, len(nodes))
    return content
