---
- name: Master HPC Provisioning Playbook
  hosts: all
  gather_facts: true
  become: true
  vars_files:
    - ../../../automation/ansible/group_vars/all.yml

  tasks:
    - name: Display starting banner
      ansible.builtin.debug:
        msg: "🚀 Starting full HPC provisioning for {{ inventory_hostname }}"



- import_playbook: ../../../automation/ansible/playbook_library/storage/storage_nfs_server.yml
  vars:
    nfs_server_service: nfs-server
    nfs_server_state: started
    nfs_server_enabled: true
    nfs_server_install_if_missing: true

    # Multiple NFS export points
    nfs_exports:
      - path: "{{ rpm_stack_path }}"
        clients: "*"
        options: ro,sync,no_root_squash
      - path: "{{ configuration_dir_path }}"
        clients: "*"
        options: rw,sync,no_root_squash
      - path: "{{ bin_dir_path }}"
        clients: "*"
        options: rw,sync,no_root_squash
