---
- name: Master HPC Provisioning Playbook
  hosts: all
  gather_facts: true
  become: true
  vars_files:
    - ../../../automation/ansible/group_vars/all.yml

  tasks:
    - name: Display starting banner
      ansible.builtin.debug:
        msg: "🚀 Starting full HPC provisioning for {{ inventory_hostname }}"


- import_playbook: ../../../automation/ansible/playbook_library/security/configure_firewall.yml
  vars:
    fw_service_name: firewalld
    fw_service_state: stopped       # Example of overriding variable
    fw_service_enabled: false       # Custom value
    fw_install_if_missing: true

